name: Check Swimming Slots

on:
  schedule:
    - cron: '0,17,36,49 * * * *'  # Runs four times an hour
  workflow_dispatch:

jobs:
  check_slots:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  # Specify the Ruby version you need

      - name: Install dependencies
        run: |
          gem install telegram-bot-ruby

      - name: Run check_swimming_slots.rb
        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: ruby check_swimming_slots.rb
